export const areas = [
  { slug: "bel-air-park", name: "Bel Air Park", region: "Georgetown", note: "Gated homes and the prices diaspora buyers ask for first." },
  { slug: "bel-air", name: "Bel Air", region: "Georgetown", note: "Residential streets beside the park." },
  { slug: "queenstown", name: "Queenstown", region: "Georgetown", note: "Older houses close to the commercial core." },
  { slug: "kitty", name: "Kitty", region: "Georgetown", note: "Family houses near the seawall." },
  { slug: "campbellville", name: "Campbellville", region: "Georgetown", note: "Central family neighbourhood." },
  { slug: "lamaha-gardens", name: "Lamaha Gardens", region: "Georgetown", note: "Established residential streets." },
  { slug: "prashad-nagar", name: "Prashad Nagar", region: "Georgetown", note: "Scheme houses near the city." },
  { slug: "subryanville", name: "Subryanville", region: "Georgetown", note: "Small residential pocket beside Bel Air." },
  { slug: "alberttown", name: "Alberttown", region: "Georgetown", note: "Older streets near the centre." },
  { slug: "cummingsburg", name: "Cummingsburg", region: "Georgetown", note: "Offices and mixed buildings." },
  { slug: "kingston", name: "Kingston", region: "Georgetown", note: "Seawall edge of the city." },
  { slug: "ruimveldt", name: "Ruimveldt", region: "Georgetown", note: "South Georgetown family houses." },
  { slug: "festival-city", name: "Festival City", region: "Georgetown", note: "Scheme housing in south Georgetown." },
  { slug: "ogle", name: "Ogle", region: "East Coast Demerara", note: "Rentals near the airstrip and oil corridor." },
  { slug: "better-hope", name: "Better Hope", region: "East Coast Demerara", note: "East Coast housing schemes." },
  { slug: "plaisance", name: "Plaisance", region: "East Coast Demerara", note: "Village on the city boundary." },
  { slug: "beterverwagting", name: "Beterverwagting", region: "East Coast Demerara", note: "Houses along the public road." },
  { slug: "mon-repos", name: "Mon Repos", region: "East Coast Demerara", note: "Market village on the East Coast." },
  { slug: "lusignan", name: "Lusignan", region: "East Coast Demerara", note: "Scheme and village housing." },
  { slug: "buxton", name: "Buxton", region: "East Coast Demerara", note: "Historic village, houses and land." },
  { slug: "enmore", name: "Enmore", region: "East Coast Demerara", note: "Houses and house lots past Buxton." },
  { slug: "mahaica", name: "Mahaica", region: "East Coast Demerara", note: "Eastern end of the coast road." },
  { slug: "eccles", name: "Eccles", region: "East Bank Demerara", note: "Schemes close to Georgetown." },
  { slug: "providence", name: "Providence", region: "East Bank Demerara", note: "Land and schemes near the stadium." },
  { slug: "diamond", name: "Diamond", region: "East Bank Demerara", note: "A main search for family houses." },
  { slug: "herstelling", name: "Herstelling", region: "East Bank Demerara", note: "Between Providence and Diamond." },
  { slug: "mocha", name: "Mocha", region: "East Bank Demerara", note: "Houses and house lots." },
  { slug: "soesdyke", name: "Soesdyke", region: "East Bank Demerara", note: "Junction on the Linden highway." },
  { slug: "vreed-en-hoop", name: "Vreed-en-Hoop", region: "West Coast Demerara", note: "The town across the new bridge." },
  { slug: "parika", name: "Parika", region: "East Bank Essequibo", note: "Market town and stelling." },
  { slug: "tuschen", name: "Tuschen", region: "West Coast Demerara", note: "West Coast housing schemes." },
  { slug: "leonora", name: "Leonora", region: "West Coast Demerara", note: "Village houses and land." },
  { slug: "new-amsterdam", name: "New Amsterdam", region: "Berbice", note: "Berbice town houses." },
  { slug: "rose-hall", name: "Rose Hall", region: "Berbice", note: "Corentyne town." },
  { slug: "corriverton", name: "Corriverton", region: "Berbice", note: "Eastern Corentyne town." },
  { slug: "rosignol", name: "Rosignol", region: "Berbice", note: "West Berbice river crossing." },
  { slug: "linden", name: "Linden", region: "Upper Demerara", note: "Mining town up the Demerara." },
  { slug: "bartica", name: "Bartica", region: "Cuyuni-Mazaruni", note: "Essequibo river town." },
  { slug: "lethem", name: "Lethem", region: "Rupununi", note: "Border town, a thin market." },
  { slug: "anna-regina", name: "Anna Regina", region: "Essequibo", note: "Essequibo coast town." }
];
