export type Listing = { id: string; title: string; area: string; region: string; type: "House" | "Apartment" | "Land" | "Commercial"; purpose: "Sale" | "Rent"; priceGyd: number; beds: number; baths: number; sqft: number; lat: number; lng: number; featured: boolean; status: "live"; agentId: string; image: string; amenities: string[]; description: string; views: number };
export const agents = [
  { id: "a1", name: "Priya Ramcharran", company: "Demerara Realty", phone: "5926001101", areas: ["Bel Air Park", "Queenstown", "Kitty"], rating: 4.9, reviews: 41, verified: true },
  { id: "a2", name: "Marcus Singh", company: "Coastal Keys", phone: "5926002202", areas: ["Ogle", "Providence"], rating: 4.7, reviews: 28, verified: true },
  { id: "a3", name: "Anita Persaud", company: "Berbice Homes", phone: "5926003303", areas: ["New Amsterdam"], rating: 4.8, reviews: 19, verified: true }
];
export const listings: Listing[] = [
  { id: "gy-1042", title: "Raised timber house, Bel Air Park", area: "Bel Air Park", region: "Georgetown", type: "House", purpose: "Sale", priceGyd: 95000000, beds: 4, baths: 3, sqft: 3200, lat: 6.8095, lng: -58.1458, featured: true, status: "live", agentId: "a1", image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80", amenities: ["Gated"], description: "Raised family house. Title transport available for attorney review.", views: 842 },
  { id: "gy-1108", title: "Apartment near the oil corridor, Ogle", area: "Ogle", region: "East Coast Demerara", type: "Apartment", purpose: "Rent", priceGyd: 420000, beds: 2, baths: 2, sqft: 1180, lat: 6.8068, lng: -58.1054, featured: true, status: "live", agentId: "a2", image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80", amenities: ["Furnished"], description: "Furnished two-bedroom near the Ogle airstrip.", views: 1204 },
  { id: "gy-1210", title: "Residential land, Providence", area: "Providence", region: "East Bank Demerara", type: "Land", purpose: "Sale", priceGyd: 18000000, beds: 0, baths: 0, sqft: 8000, lat: 6.7714, lng: -58.1688, featured: false, status: "live", agentId: "a2", image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80", amenities: ["Survey plan"], description: "Corner residential lot near the stadium corridor.", views: 311 },
  { id: "gy-1333", title: "Office suite, Main Street", area: "Cummingsburg", region: "Georgetown", type: "Commercial", purpose: "Rent", priceGyd: 650000, beds: 0, baths: 2, sqft: 2100, lat: 6.8128, lng: -58.1556, featured: false, status: "live", agentId: "a2", image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80", amenities: ["Parking"], description: "Second-floor office on the commercial strip.", views: 188 },
  { id: "gy-1402", title: "New Amsterdam riverside house", area: "New Amsterdam", region: "Berbice", type: "House", purpose: "Sale", priceGyd: 28000000, beds: 3, baths: 2, sqft: 1540, lat: 6.2479, lng: -57.5172, featured: false, status: "live", agentId: "a3", image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80", amenities: ["River view"], description: "Raised house near the New Amsterdam market.", views: 276 }
];
export const money = (n: number, purpose: string) => `GYD ${n.toLocaleString()}${purpose === "Rent" ? " / month" : ""}`;
export const usd = (n: number) => Math.round(n / 209);
export const agentById = (id: string) => agents.find((a) => a.id === id) || agents[0];
export const listingById = (id: string) => listings.find((l) => l.id === id);
